config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('materials.urls')),
    path('user/', include('user.urls')),
]

materials/urls.py
from django.urls import path
from .views import CourseDetailView, CourseListView, CourseUpdateView, DashboardView, IndexView, CourseCreateView, LessonCreateView, LessonDetailView, LessonListView

app_name = 'materials'

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('course/create/', CourseCreateView.as_view(), name='course_create'),
    path('courses/<int:course_id>/lessons/create/',
         LessonCreateView.as_view(), name='lesson_create'),
    path('lessons/<int:pk>/', LessonDetailView.as_view(), name='lesson_detail'),
    path('courses/', CourseListView.as_view(), name='course_list'),
    path('courses/<int:pk>/', CourseDetailView.as_view(), name='course_detail'),
    path('courses/<int:course_id>/lessons/',
         LessonListView.as_view(), name='lesson_list'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('courses/<int:pk>/update/',
         CourseUpdateView.as_view(), name='course_update'),

]

user/urls.py
from django.urls import path
from user.views import UserActivateView, UserCreateView, UserDetailView, UserUpdateView, login_view

app_name = 'user'

urlpatterns = [
    path('create/', UserCreateView.as_view(), name='create_user'),
    path('activate/<uidb64>/<token>/',
         UserActivateView.as_view(), name='activate_user'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='profile'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='update'),
    path('login/', login_view, name='login')

]

materials/models.py
from django.db import models


NULLABLE = {'null': True, 'blank': True}


class Course(models.Model):
    """Модель курса"""
    title = models.CharField(
        max_length=255, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    author = models.ForeignKey(
        'user.User', on_delete=models.CASCADE, verbose_name='Урок')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Курс'
        verbose_name_plural = 'Курсы'


class Lesson(models.Model):
    """Модель урока"""
    course = models.ForeignKey(
        Course, on_delete=models.CASCADE, verbose_name='Курс')
    title = models.CharField(
        max_length=255, verbose_name='Название')
    content = models.TextField(verbose_name='Материал урока', **NULLABLE)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Урок'
        verbose_name_plural = 'Уроки'


class Answer(models.Model):
    lesson = models.ForeignKey(
        Lesson, on_delete=models.CASCADE, verbose_name='урок')
    question = models.TextField(
        verbose_name='Материал урока')
    correct_answer = models.CharField(
        max_length=150, verbose_name='Название')

materials/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic import CreateView, UpdateView, DetailView, ListView
from user.models import CompletedTasks
from materials.models import Answer, Course, Lesson
from django.contrib import messages
from user.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin


class IndexView(TemplateView, LoginRequiredMixin):
    template_name = 'materials/index.html'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     # Получаем список курсов, созданных текущим пользователем
    #     user = self.request.user
    #     context['created_courses'] = Course.objects.filter(author=user)
    #     # Получаем список всех курсов
    #     context['courses'] = Course.objects.all()
    #     return context

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)

    #     user = self.request.user
    #     created_courses = Course.objects.filter(author=user)
    #     print("Created courses:", created_courses)

    #     all_courses = Course.objects.all()
    #     print("All courses:", all_courses)
    #     context['created_courses'] = created_courses
    #     context['courses'] = all_courses
    #     return context


class CourseCreateView(CreateView, LoginRequiredMixin):
    model = Course
    fields = ['title', 'description']

    def get_success_url(self):

        course_id = self.object.pk

        return reverse_lazy('materials:lesson_create', kwargs={'course_id': course_id})

    def form_valid(self, form):

        form.instance.author = self.request.user
        return super().form_valid(form)


class CourseListView(ListView, LoginRequiredMixin):
    model = Course
    template_name = 'materials/courses_list.html'
    context_object_name = 'courses'


class CourseDetailView(DetailView, LoginRequiredMixin):
    model = Course
    template_name = 'materials/course_detail.html'
    context_object_name = 'course'


class LessonCreateView(CreateView, LoginRequiredMixin):
    model = Lesson
    fields = ['title', 'content']
    template_name = 'materials/lesson_form.html'

    def form_valid(self, form):
        course_id = self.kwargs['course_id']
        form.instance.course_id = course_id
        super().form_valid(form)
        data = self.request.POST
        for key, value in data.items():
            if key.startswith('question_'):
                index = key.split('_')[1]
                question = value
                answer = data['answer_' + index]
                Answer.objects.create(
                    lesson=form.instance, question=question, correct_answer=answer)

        return super().form_valid(form)

    def get_success_url(self):
        course_id = self.kwargs['course_id']
        return reverse_lazy('materials:lesson_list', kwargs={'course_id': course_id})


class LessonDetailView(DetailView, LoginRequiredMixin):
    model = Lesson
    template_name = 'materials/lesson_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lesson = self.get_object()
        user = self.request.user
        context['questions'] = Answer.objects.filter(lesson=lesson)
        context['completed_tasks'] = CompletedTasks.objects.filter(user=user)
        return context

    def post(self, request, *args, **kwargs):
        lesson = self.get_object()
        user = request.user
        for question in lesson.answer_set.all():
            answer_text = request.POST.get(str(question.id))
            completed_task = CompletedTasks.objects.filter(
                user=user, answer=question).first()
            if completed_task and completed_task.is_correct:
                messages.error(request, f"You've already answered question '{
                               question.question}' correctly.")
            else:
                is_correct = self.check_answer_correctness(
                    question.id, answer_text)
                if is_correct:
                    CompletedTasks.objects.create(
                        user=user, answer=question, is_correct=True)
                else:
                    messages.error(request, f"Your answer to question '{
                                   question.question}' is incorrect.")
        return redirect('materials:lesson_detail', pk=lesson.pk)

    def check_answer_correctness(self, question_id, answer_text):
        question = Answer.objects.get(pk=question_id)
        correct_answer = question.correct_answer
        return answer_text.strip().lower() == correct_answer.strip().lower()


class LessonListView(ListView, LoginRequiredMixin):
    model = Lesson
    template_name = 'materials/lesson_list.html'
    context_object_name = 'lessons'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        course_id = self.kwargs.get('course_id')
        course = Course.objects.get(pk=course_id)

        context['course'] = course
        return context


class DashboardView(TemplateView, LoginRequiredMixin):
    template_name = 'materials/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        created_courses = Course.objects.filter(author=self.request.user)
        context['created_courses'] = created_courses

        all_courses = Course.objects.all()
        context['courses'] = all_courses
        return context


class CourseUpdateView(UserPassesTestMixin, UpdateView):
    model = Course
    fields = ['title', 'description']
    template_name = 'materials/course_update.html'
    context_object_name = 'course'
    success_url = reverse_lazy('materials:dashboard')

    def test_func(self):

        course = self.get_object()

        return self.request.user == course.author

    def handle_no_permission(self):

        return redirect('home')

materials/templates/materials/course_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ course.title }}</title>
</head>
<body>
    <h1>{{ course.title }}</h1>
    <p>{{ course.description }}</p>
    
    <!-- Кнопка или ссылка для перехода к списку уроков -->
    <a href="{% url 'materials:lesson_list' course.id %}">Список уроков</a>
</body>
</html>

materials/templates/materials/course_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация</title>
    <style>
        /* Простой CSS для стилизации формы */
        form {
            max-width: 300px;
            margin: 0 auto;
        }

        label {
            display: block;
            margin-bottom: 5px;
        }

        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 8px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        input[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        input[type="submit"]:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <!-- course_form.html -->
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Создать курс</button>
  </form>
  
</body>
</html>

materials/templates/materials/course_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Редактирование курса</title>
</head>
<body>
    <h1>Редактирование курса</h1>
    <form method="post">
        {% csrf_token %}
        <label for="title">Название курса:</label><br>
        <input type="text" id="title" name="title" value="{{ course.title }}" required><br><br>
        
        <label for="description">Описание курса:</label><br>
        <textarea id="description" name="description" required>{{ course.description }}</textarea><br><br>
        
        <button type="submit">Сохранить изменения</button>
    </form>
</body>
</html>

materials/templates/materials/courses_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Выбор курса</title>
</head>
<body>
    <h1>Выберите курс</h1>
    <ul>
        {% for course in courses %}
        <li><a href="{% url 'materials:course_detail' course.id %}">{{ course.title }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

materials/templates/materials/dashboard.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Панель управления</title>
    <style>
        * {
            box-sizing: border-box;
        }

        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
            color: #333;
        }

        h1, h2 {
            text-align: center;
            padding: 20px 0;
        }

        .btn {
            display: inline-block;
            padding: 10px 20px;
            margin: 5px 0;
            border: none;
            color: #fff;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
            text-decoration: none;
        }

        .btn-primary {
            background-color: #3498db;
        }

        .btn-primary:hover {
            background-color: #2980b9;
        }

        .btn-secondary {
            background-color: #2ecc71;
        }

        .btn-secondary:hover {
            background-color: #27ae60;
        }

        ul {
            list-style-type: none;
            padding: 0;
            width: 100%;
            max-width: 600px;
            margin: 0 auto;
        }

        li {
            background-color: #fff;
            border: 1px solid #ddd;
            margin: 10px 0;
            padding: 10px;
            border-radius: 5px;
        }

        a {
            color: #3498db;
        }

        a:hover {
            color: #2980b9;
        }
    </style>
</head>
<body>
    <h1>Панель управления</h1>

    <div style="text-align: center;">
        <a href="{% url 'user:profile' user.pk %}" class="btn btn-primary">Профиль</a>
    </div>
    <!-- Кнопка для создания курса -->
    <div style="text-align: center;">
        <a href="{% url 'materials:course_create' %}" class="btn btn-primary">Создать курс</a>
    </div>

    <h2>Мои созданные курсы</h2>
    <ul>
        {% for course in created_courses %}
            <li>
                <a href="{% url 'materials:course_detail' course.id %}">{{ course.title }}</a>
                {% if user == course.author %}
                    <a href="{% url 'materials:course_update' course.id %}" class="btn btn-secondary">Изменить</a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>

    <h2>Все курсы</h2>
    <ul>
        {% for course in courses %}
            <li><a href="{% url 'materials:course_detail' course.id %}">{{ course.title }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

materials/templates/materials/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Моя страница</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f9f9f9;
        }

        h1 {
            color: #333;
            text-align: center;
            padding: 20px 0;
        }

        .button-container {
            display: flex;
            justify-content: center;
            gap: 20px;
            padding: 20px 0;
        }

        .button {
            display: inline-block;
            padding: 10px 20px;
            font-size: 16px;
            cursor: pointer;
            text-decoration: none;
            border: none;
            background-color: #007BFF;
            color: #fff;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }

        .button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <h1>Добро пожаловать!</h1>
    <div class="button-container">
        <a href="/user/login/" class="button">Вход</a>
        <a href="/user/create/" class="button">Регистрация</a>
    </div>
</body>
</html>

materials/templates/materials/lesson_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ object.title }}</title>
</head>
<body>
    <h1>{{ object.title }}</h1>
    <p>{{ object.content }}</p>

    {% for message in messages %}
        <div>{{ message }}</div>
    {% endfor %}

    <h2>Вопросы к уроку:</h2>
    <form method="post">
        {% csrf_token %}
        <ul>
            {% for question in questions %}
                <li>{{ question.question }}</li>
                <input type="text" name="{{ question.id }}">
            {% endfor %}
        </ul>
        <button type="submit">Отправить ответы</button>
    </form>
</body>
</html>

materials/templates/materials/lesson_form.html
  



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация</title>
    <style>
    </style>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <label for="id_title">Название урока:</label>
        <input type="text" id="id_title" name="title" required>
        <br>
        <label for="id_content">Материал урока:</label>
        <textarea id="id_content" name="content" required></textarea>
        <br>
        <!-- Добавляем вопросы с ответами -->
        <h2>Вопросы с ответами</h2>
        <div id="questions">
          <div class="question">
            <label for="id_question_0">Вопрос:</label>
            <textarea id="id_question_0" name="question_0" required></textarea>
            <br>
            <label for="id_answer_0">Ответ:</label>
            <input type="text" id="id_answer_0" name="answer_0" required>
          </div>
        </div>
        <button type="button" id="add_question">Добавить вопрос</button>
        <br>
        <button type="submit">Создать урок</button>
      </form>
      
      <script>
        document.getElementById('add_question').addEventListener('click', function() {
          var questionsDiv = document.getElementById('questions');
          var questionCount = questionsDiv.getElementsByClassName('question').length;
      
          var newQuestionDiv = document.createElement('div');
          newQuestionDiv.classList.add('question');
      
          var questionLabel = document.createElement('label');
          questionLabel.htmlFor = 'id_question_' + questionCount;
          questionLabel.textContent = 'Вопрос:';
          newQuestionDiv.appendChild(questionLabel);
      
          var questionTextarea = document.createElement('textarea');
          questionTextarea.id = 'id_question_' + questionCount;
          questionTextarea.name = 'question_' + questionCount;
          questionTextarea.required = true;
          newQuestionDiv.appendChild(questionTextarea);
      
          var lineBreak = document.createElement('br');
          newQuestionDiv.appendChild(lineBreak);
      
          var answerLabel = document.createElement('label');
          answerLabel.htmlFor = 'id_answer_' + questionCount;
          answerLabel.textContent = 'Ответ:';
          newQuestionDiv.appendChild(answerLabel);
      
          var answerInput = document.createElement('input');
          answerInput.type = 'text';
          answerInput.id = 'id_answer_' + questionCount;
          answerInput.name = 'answer_' + questionCount;
          answerInput.required = true;
          newQuestionDiv.appendChild(answerInput);
      
          questionsDiv.appendChild(newQuestionDiv);
        });
      </script>
  
</body>
</html>

materials/templates/materials/lesson_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Список уроков</title>
</head>
<body>
    <h1>Список уроков для курса "{{ course.title }}"</h1>
    <ul>
        {% for lesson in lessons %}
            <li><a href="{% url 'materials:lesson_detail' lesson.pk %}">{{ lesson.title }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>