config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('materials.urls')),
    path('user/', include('user.urls')),
]

user/urls.py
from django.urls import path
from user.views import UserActivateView, UserCreateView, UserDetailView, UserUpdateView, login_view

app_name = 'user'

urlpatterns = [
    path('create/', UserCreateView.as_view(), name='create_user'),
    path('activate/<uidb64>/<token>/',
         UserActivateView.as_view(), name='activate_user'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='profile'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='update'),
    path('login/', login_view, name='login')

]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from materials.models import Answer


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=128, verbose_name='пароль')
    is_active = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email


class CompletedTasks(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='Урок')
    answer = models.ForeignKey(
        Answer, on_delete=models.CASCADE, verbose_name='Урок')
    is_correct = models.BooleanField(default=False)

user/views.py
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, UpdateView, DetailView
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth import get_user_model
from django.contrib.auth.tokens import default_token_generator
from django.http import Http404
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from user.models import User
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages


class UserCreateView(CreateView):
    model = User
    fields = ('email', 'password',)
    success_url = reverse_lazy('materials:home')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.set_password(form.cleaned_data['password'])
        user.save()

        self.send_activation_email(user)

        return super().form_valid(form)

    def send_activation_email(self, user):
        current_site = get_current_site(self.request)
        mail_subject = 'Активация учетной записи'

        uid = urlsafe_base64_encode(force_bytes(user.pk))
        token = default_token_generator.make_token(user)

        message = render_to_string('user/activation_email.html', {
            'user': user,
            'domain': current_site.domain,
            'uidb64': uid,
            'token': token,
        })
        send_mail(mail_subject, message, 'w4atifif@yandex.ru', [user.email])


class UserActivateView(View):
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = get_user_model().objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            return redirect('materials:home')
        else:
            raise Http404


def login_view(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)

            return redirect('materials:dashboard')
        else:

            messages.error(
                request, 'Неверный адрес электронной почты или пароль.')
            return render(request, 'user/login.html')

    return render(request, 'user/login.html')


class UserDetailView(DetailView):
    model = User

    def get_object(self):

        user = get_object_or_404(User, pk=self.kwargs['pk'])

        print("User detail:", user)
        return user


class UserUpdateView(UpdateView):
    model = User
    fields = ['first_name', 'last_name']
    template_name = 'user/user_update_form.html'

    def get_success_url(self):
        return reverse_lazy('user:profile', kwargs={'pk': self.object.pk})

user/templates/user/acc_active_email.html
{% autoescape off %}
Привет {{ user.email }},
Спасибо за регистрацию.
Пожалуйста, перейдите по ссылке ниже, чтобы активировать ваш аккаунт:
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
Если у вас возникли проблемы, пожалуйста, свяжитесь с нами.
С уважением,
Ваша команда сайта
{% endautoescape %}

user/templates/user/activation_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Activation Email</title>
</head>
<body>
    <h2>Добро пожаловать, {{ user.email }}!</h2>
    <p>Для активации вашей учетной записи, пожалуйста, перейдите по следующей ссылке:</p>
    <a href="http://{{ domain }}{% url 'user:activate_user' uidb64 token %}">Активировать учетную запись</a>
    <p>Спасибо за регистрацию!</p>
</body>
</html>

user/templates/user/activation_invalid.html
<!DOCTYPE html>
<html>
<head>
    <title>Активация недействительна</title>
</head>
<body>
    <h1>Извините, ваша активация недействительна</h1>
    <p>Пожалуйста, проверьте свою электронную почту и следуйте инструкциям для активации вашего аккаунта.</p>
</body>
</html>

user/templates/user/login.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Вход</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f9f9f9;
        }

        h2 {
            color: #333;
            text-align: center;
            padding: 20px 0;
        }

        form {
            display: flex;
            flex-direction: column;
            align-items: center;
            gap: 10px;
            padding: 20px 0;
        }

        input {
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        button {
            padding: 10px 20px;
            border: none;
            background-color: #007BFF;
            color: #fff;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <h2>Вход</h2>
    
    <!-- Выводим сообщения об ошибках -->
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    
    <form method="post" action="{% url 'user:login' %}">
        {% csrf_token %}
        <div>
            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required>
        </div>
        <div>
            <label for="password">Пароль:</label>
            <input type="password" id="password" name="password" required>
        </div>
        <button type="submit">Войти</button>
    </form>
</body>
</html>

user/templates/user/user_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация</title>
    <style>
        /* Простой CSS для стилизации формы */
        form {
            max-width: 300px;
            margin: 0 auto;
        }

        label {
            display: block;
            margin-bottom: 5px;
        }

        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 8px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        input[type="submit"],
        button {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            margin-bottom: 10px;
        }

        input[type="submit"]:hover,
        button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <h2>Профиль пользователя</h2>
  <table>
    <tr>
      <th>Email:</th>
      <td>{{ user.email }}</td>
    </tr>
    <tr>
      <th>Имя:</th>
      <td>{{ user.first_name }}</td>
    </tr>
    <tr>
      <th>Фамилия:</th>
      <td>{{ user.last_name }}</td>
    </tr>
    
    <tr>
      <th>Активен:</th>
      <td>{{ user.is_active }}</td>
    </tr>
  </table>
  <button onclick="window.location.href='/user/update/{{ user.pk }}/'">Изменить</button>
</body>
</html>

user/templates/user/user_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация</title>
    <style>
        /* Простой CSS для стилизации формы */
        form {
            max-width: 300px;
            margin: 0 auto;
        }

        label {
            display: block;
            margin-bottom: 5px;
        }

        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 8px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        input[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        input[type="submit"]:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <h2>Регистрация</h2>
    <form action="/user/create/" method="post">
        {% csrf_token %} 
        <div>
            <label for="email">Email:</label>
            <input type="text" id="email" name="email" required>
        </div>
        <div>
            <label for="password">Пароль:</label>
            <input type="password" id="password" name="password" required>
        </div>
        <div>
            <input type="submit" value="Зарегистрироваться">
        </div>
    </form>
</body>
</html>

user/templates/user/user_update_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <form method="POST" action="{% url 'user:update' pk=user.pk %}">
        {% csrf_token %}
        <label for="first_name">Имя:</label><br>
        <input type="text" id="first_name" name="first_name" value="{{ user.first_name }}"><br>
        <label for="last_name">Фамилия:</label><br>
        <input type="text" id="last_name" name="last_name" value="{{ user.last_name }}"><br>
        <input type="submit" value="Обновить">
    </form>
</body>
</html>